### ISSUE TITLE
Is this still worth trying out?

### ISSUE THREAD

**Issue by mfirry** [enieber/reasonml-api#1]
two years in and I wonder if this is a good thing try (i'm making my first steps in reason).
are you planning on update this?

**Comment by enieber** [comment]
I like much Reasonml and started developing the [re-http](https://github.com/enieber/re-http) to help create API in reason to compile Nodejs application.

The benefit of using the Reasonml compile to js is one js with less error.

I expected finish the version of re-http to use like [bs-express](https://github.com/reasonml-community/bs-express) or [serbet](https://github.com/mrmurphy/serbet)

To send one version to use of Re-http I need [finish this PR](https://github.com/enieber/re-http/pull/5)

**Comment by mfirry** [comment]
Thanks. I will follow re-http then.
